language: node_js
node_js:
  - '8'
  - '10'
  - '12'
services:
  - postgresql
before_script:
  - psql -c 'create database "refresh-token-test"' -U postgres
  - ./node_modules/.bin/knex migrate:latest --env test
