language: node_js
node_js:
  - '4'
  - '6'
services:
  - postgresql
before_script:
  - psql -c 'create database "refresh-token-test"' -U postgres
  - ./node_modules/.bin/knex migrate:latest --env test
sudo: false
